apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-hello
  template:
    metadata:
      labels:
        app: node-hello
    spec:
      containers:
        - name: node-hello
          image: rohanshinde08/node-hello
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-hello-service
spec:
  selector:
    app: node-hello
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30000
  type: NodePort
